# Customize the codemagic.yaml file according to your project and commit it to the root of your repository
# Check out https://docs.codemagic.io/getting-started/yaml/ for more information
# You can also download your configuration from Worklow Editor to get started

workflows:
  android-workflow:
    name: Build for Android
    scripts:
      - name: Build APK
        script: flutter build apk
    publishing:
      email:
        recipients:
          - thaiivts@example.com
  ios-workflow:
    name: Build for iOS
    scripts:
      - name: Build IPA
        script: flutter build ios
    publishing:
      email:
        recipients:
          - thaiivts@example.com